name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest, macos-13]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build application
        run: make
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mogit-${{ matrix.platform }}
          path: dist/